### PR TITLE
Added type capability annotations

### PR DESCRIPTION
**Pull request by grubeninspekteur**
Added missing type and feature capabilities to some tools

### CODE REVIEW

**Comment by reckart** [comment]
Thanks Tim. Are the "feature capabilities" relevant to you? We normally only add simple type capabilities that do not state any features.

**Comment by grubeninspekteur** [comment]
Not in particular. I just read in the UIMA reference that all modifications made by an Analysis Engine should be listed. I'm working on a tool that performs a type check on pipelines. It could be, for example, that a POS tagger produces only annotations, but does not modify the 'pos' feature of the token annotation, which is read by most of (all?) DKPro annotators further down in place of the annotation. But then again, the types that depend on parameter settings like in the case of the Stanford Parser can't be expressed in the descriptor anyway.

**Comment by reckart** [comment]
Per (unwritten) convention, the "pos" feature must be set by a POS annotator. But in general you are right, not all annotators always set all features.

**Comment by grubeninspekteur** [comment]
Removed the feature type capabilities and squashed the commits

**Pull request merged**
