### PR TITLE
#1180: Option to markup split tokens in CamelCaseTokenSegmenter

### PR DESCRIPTION
**Pull request by mjunsilo**
Jut let me know what I need to change.

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by mjunsilo** [comment]
I have tested the behaviour of this component in a wider context, and it appears overly eager in its splitting behaviour, e.g. it splits "STDs" into "ST" and "Ds", which can always be discussed whether that is proper camel casing and where it should be split, if at all. However, I think this is another issue, so we should merge this, and I can create another issue regarding the behaviour.

**Comment by reckart** [comment]
👍

**Pull request merged**
