### PR TITLE
Arabic segmentation with CoreNLP

### PR DESCRIPTION
**Pull request by Jibun**
Changes as discussed in #1216

I have finally changed `followRedirects` function in `ResourceObjectProviderBase` to return a null URL if the model is not required. And then it is managed from the `configure` method.

I have also included the changes in the pom to load the new Arabic model. **However, this will crash until DKPro repo includes it.**

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@Jibun could you have a look at resolving the conflicts?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@Jibun When I check out the branch, I can see that there are some formatting issues in the `CoreNlpSegmenterTest.testArabic()`. We use checkstyle. Depending on what IDE you use, you can install a Checkstyle plugin / Maven checkstyle configurator to see the style issues directly in your IDE - or you can run a Maven build of the module on the command line. E.g. for Eclipse:
* Install Checkstyle Eclipse plugin from here: http://eclipse-cs.sourceforge.net
* Install the Checkstyle configuration plugin for M2Eclipse from here: http://m2e-code-quality.github.com/m2e-code-quality/site/latest/

I tried to fix the changes and to push them into this PR, but it seems that when you created the PR, you didn't check the box that allows the target repo committers to push changes into your branch.

It would be great if you could fix the checkstyle issues.

I have uploaded the segmenter model to the Maven repo now, so the PR should work (and I can successfully run the tests on my machine).

Looking forward to merging this 👍

**Comment by Jibun** [comment]
@reckart I run a maven build and no checkstyle errors were reported (maybe because I had to disable the tests). Just to double check I have downloaded the eclipse checkstyle plugin and it still doesn't find style errors.
Could you tell me what are they exactly, so I can fix them?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@Jibun can you please check if you still see a checkbox somewhere in the PR where you can allow me to push changes into this PR?

**Comment by Jibun** [comment]
@reckart Let me uncheck and check again

**Comment by Jibun** [comment]
@reckart done

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
