### PR TITLE
StanfordSegmenter: add missing @TypeCapability

### PR DESCRIPTION
**Pull request by schrieveslaach**

### CODE REVIEW

**Comment by betoboullosa** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
I think Jenkins doesn't like us anymore...

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by schrieveslaach** [comment]
I cannot figure out why the check failed. Do I have to change the code?

**Comment by reckart** [comment]
It failed because I aborted the build so that @betoboullosa can try triggering it again. Sorry for using this PR as a guinea pig ;)

**Comment by schrieveslaach** [comment]
OK, understood. 😉

**Comment by betoboullosa** [comment]
Jenkins, can you test this please?

**Comment by betoboullosa** [comment]
Jenkins, can you test this please?

**Comment by betoboullosa** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@betoboullosa When merge-squashing this one, instead of using this PR's issue number and title, I would suggest to use

*Title*: #938 - Add missing capability annotations (1.9.0)

*Message:*
```
- StanfordSegmenter: add missing @TypeCapability
```

**Pull request merged**
