### PR TITLE
#1308 - integrate mystem

### PR DESCRIPTION
**Pull request by Horsmann**

### CODE REVIEW

**Comment by Horsmann** [comment]
@reckart do you upload the binaries?

**Comment by reckart** [comment]
@Horsmann not yet - although it seems they must still be staged because my Eclipse automatically downloaded a binary JAR...

**Comment by Horsmann** [comment]
Hm, ok - I might have uploaded them already. I honestly don't remember. Its too long ago that I touched this the last time.

**Comment by reckart** [comment]
:) I moved the staged artifact to the model repo now.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by Horsmann** [comment]
It seems I am not authorized to merge?

**Pull request merged**
