### PR TITLE
BratWriter does not deal properly with filenames that contain spaces #1392

### PR DESCRIPTION
**Pull request by alaindesilets**
I have implemented and tested the fix for this and would like to incorporate it in 1.11.x

### CODE REVIEW

**Comment by reckart** [comment]
Looks like this PR is based on the master branch but the target is the 1.11.x branch. Could you please force-push or redo the PR with changes against the 1.11.x branch?

**Comment by alaindesilets** [comment]
On Mon, Jul 15, 2019 at 12:45 PM Richard Eckart de Castilho <
notifications@github.com> wrote:

> Looks like this PR is based on the master branch but the target is the
> 1.11.x branch. Could you please force-push or redo the PR with changes
> against the 1.11.x branch?
>

This is my first ever pull request, so I don't quite know what I am doing. f

Can you describe to me the process for:
- creating the patch
- creating a pull request for it.

What I have done so far is to create mirror of 1.11.x on my local machine
and do the patch there. Not sure what to do next exactly.

**Comment by reckart** [comment]
Ok, let's see. Looking at this PR again, I can see that it is actually set up to merge our master branch into our 1.11.x branch - the PR doesn't actually involve your repo/change at all.

What you should locally have now is at least a branch based on 1.11.x called something like `feature/1392-BratWriter -has-trouble-with-spaces` and your changes should be committed to that branch.

Make sure that you push the local branch on which you made your changes to your fork of the DKPro Core repo on GitHub. If you did not yet create a fork on GitHub, do it now using the "fork" button at the top of the page. Then add your forked repository as an additional remote repository to your local clone and push your local feature branch there. I'm using Sourcetree and adding remotes can be done there under "Settings / Remotes".

Once you pushed this branch, visit your forked repo on GitHub. If you do it shortly after pushing the branch, probably a message appears asking if you want to create a PR based on your branch. If it does not appear, manually create a new PR *in your own forked repo* - choose 1.11.x branch of our repo as the target branch.

I think we can safely discard the present PR in favor of the new one that you are going to create.

**Comment by alaindesilets** [comment]
OK, I understand. Thanks for your patience.

**Pull request closed without merging**
