### PR TITLE
Issue/stanford ner train should fail gracefully with empty training collection

### PR DESCRIPTION
**Pull request by alaindesilets**
This pull request deals with issue #1395: "null pointer exception in StanfordNamedEntityRecognizerTrainer"

I am still green w.r.t. issueing pull requests so I am not sure if I did this right. It seems like the branch of this pull request might be based on the branch from my earlier pull request (#1392) and I suspect that this is not a good idea. If this is wrong, please let me know and any help on how to address it would be appreciated. I have been using git for 4 years now, but I never use remote branches so I am not that familiar with how they work and how to set them up. Thank you for your patience.

### CODE REVIEW

**Comment by reckart** [comment]
Before preparing a new PR, it's always a good idea to switch back to the branch into which the PR should eventually be merged. So the other PR you did is the better one. I'm closing this one.

**Comment by alaindesilets** [comment]
Yeah, sorry about that. This is a lot of new concepts to learn for me. I am
carefully documenting the steps so hopefully my next commit will not be as
painful.

BTW: From the emails you have sent it sounds like this change has been
effected in master of dkpro-core, but when I go do this URL, I don't see
it. Is that normal?

https://github.com/dkpro/dkpro-core/blob/1.11.x/dkpro-core-stanfordnlp-gpl/src/main/java/org/dkpro/core/stanfordnlp/StanfordNamedEntityRecognizerTrainer.java

**Comment by reckart** [comment]
The PR  #1398 has not been merged yet. When it is merged, #1398 goes to the master branch (that is how you set up the PR). Since it is a bugfix, it should normally have been opened against the 1.11.x branch. I'll cherry-pick it back into 1.11.x after the merge. But better open bugfix issues against 1.11.x. Note that the master branch builds against UIMAv3 but no other DKPro code so far builds against UIMAv3. So presently, it would be better even do branches for new features against 1.11.x or 1.12.x which are still using UIMAv2.

Sorry about the confusing situation...

**Comment by alaindesilets** [comment]
Hum.. I thought you had told me to make bug fixes in 1.11.x, but I see that:
- master is now at 1.2
- there is a 1.12.x between 1.11.x and 1.2

So am I confused and should the bug fixes be done against 1.12.x instead of
1.11.x?

**Comment by reckart** [comment]
`master` is at 2.0.0-SNAPSHOT since the 1.11.0 release. The 2.0.x series is for UIMAv3.
Bugfixes should go against `1.11.x` so we can easily do a bugfix release of the 1.11.x series.
I just pushed a 1.12.x branch in case we want to add features which should be available to UIMAv2.

**Comment by reckart** [comment]
At this point...

- if we do a new feature release for UIMAv2, it would be DKPro Core 1.12.0. 
- if we do a bugfix release for UIMAv2, it will be DKPro Core 1.11.1
- the upcoming feature release for UIMAv3 is DKPro Core 2.0.0

**Comment by alaindesilets** [comment]
Crystal clear, thx.

**Pull request closed without merging**
