### PR TITLE
LingPipe NER trainer

### PR DESCRIPTION
**Pull request by schrieveslaach**

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, test this please.

**Comment by reckart** [comment]
@schrieveslaach Could you please check the Jenkins build logs. It looks like at least one file is missing a license header.

**Comment by schrieveslaach** [comment]
@reckart, done. I was not aware that you use `mvn com.mycila:license-maven-plugin:3.0:format` to generate the license header. The version I used did not work. Do you think it would be worthwhile to add such information into a [`CONTRIBUTION.md`](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)?

**Comment by reckart** [comment]
@schrieveslaach Maybe rather the [Developer Guide](https://github.com/dkpro/dkpro-core/tree/master/dkpro-core-doc/src/main/asciidoc/developer-guide)?

**Comment by reckart** [comment]
Jenkins, test this please.

**Comment by schrieveslaach** [comment]
@reckart, I looked into the build log and it tells me that Jenkins could not run `mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze-only`. However, this is working on my local machine. What is wrong with my code?

**Comment by reckart** [comment]
If you run `dependency:analyze` without `-DfailOnWarning`, then you only get the warning logged. However, our Jenkins enables `failOnWarning`.

The problem is this:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze-only (default-cli) on project de.tudarmstadt.ukp.dkpro.core.lingpipe-gpl: Cannot analyze dependencies: Trying to force use of dependencies which are declared but already detected as used: [de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.parameter-asl] -> [Help 1]
```

So it appears after you change, the Maven dependency plugin is now able to detect `de.tudarmstadt.ukp.dkpro.core.api.parameter-asl`. Before your change, Maven was not able do detect the dependency. This inability to detect that a dependency is required can happen e.g. if the only dependency is on constants which the Java compile inlines. In such cases, we explicitly configure the dependency plugin in the `pom.xml` to consider the dependency as being used. The error you see now is because the dependency plugin doesn't want to be told that a dependency is being used when it can detect that by itself. The solution is to remove the corresponding line from the pom.xml:

```
              <!--
                - Maven doesn't detect the parameters module to be used, be we actually
                - do require it as a compile dependency and also at runtime, so we
                - cannot set it to scope provided. Need to tell Maven to ignore it here.
              -->
              <usedDependency>de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.parameter-asl</usedDependency>
```

**Comment by schrieveslaach** [comment]
@reckart, I fixed the dependency problem. Thanks for your advice.

**Comment by reckart** [comment]
Jenkins, test this please.

**Pull request merged**
