### PR TITLE
Tree tagger models

### PR DESCRIPTION
**Pull request by nilsreiter**
I added an entry in the build.xml for a middle high german parameter file (gmh). And while I was at it, I also updated the checksums for (modern) English and German.

### CODE REVIEW

**Comment by reckart** [comment]
Thanks Nils. If you look at the [diff](https://github.com/dkpro/dkpro-core/pull/1043/files), unfortunately, there are many many changes in whitespace not related at all to you addition. Could you minimize the changes to the relevant sections of the file?

**Comment by nilsreiter** [comment]
I was afraid of that. Yes, I'll see to it.

**Comment by reckart** [comment]
I am asking because I was considering to accept this as a minimal change without a [CLA](http://dkpro.github.io/contributing/). Alternatively, if you could just send us a CLA, I'll be happy to merge as is.

**Comment by nilsreiter** [comment]
Well, my editor shouldn't have changed the whitespace in the first place, so I'll try to fix that first.

**Comment by nilsreiter** [comment]
Now it's better. 

Two detail infos:
- I do not know the end date for the old checksum, entering today's date seems what you did in the previous cases.
- The middle high German tagger produces universal dependencies pos tags. I stated `<entry key="pos.tagset" value="universal"/>`.

**Comment by reckart** [comment]
You can get the date of a model using `curl -I`:

```
curl -I http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/middle-high-german-par-linux-3.2-utf8.bin.gz
HTTP/1.1 200 OK
Date: Thu, 20 Apr 2017 08:49:33 GMT
Server: Apache/2.4.23 (Linux/SUSE)
Last-Modified: Mon, 07 Nov 2016 15:35:21 GMT
ETag: "32280a-540b7c598f4ad"
Accept-Ranges: bytes
Content-Length: 3287050
Content-Type: application/x-gzip
```

The `Last-Modified` date defines the new model version and also the checksum date.

**Comment by nilsreiter** [comment]
(the whitespace has been added by Atom, which by default adds removes trailing spaces)

**Comment by nilsreiter** [comment]
Hm, there could still be a model in-between. At least for the German model this seems likely, given the dates ...

**Comment by reckart** [comment]
Merging this as a minimal changed covered by the ALv2 Section 5.

**Comment by reckart** [comment]
@nilsreiter I was about to merge this, but didn't yet. If the checksums of the English and German models changed, then also the versions of them need to change. The versions need to change both, in the build.xml as well as in the pom.xml.

The version for the middle-high-german also at the moment doesn't correspond to the date returned by curl: `Last-Modified: Mon, 07 Nov 2016 15:35:21 GMT` should translate to `upstreamVersion="20161107"`.

**Comment by reckart** [comment]
> Hm, there could still be a model in-between. At least for the German model this seems likely, given the dates ...

That is not a problem. The list doesn't aim to be complete.

**Comment by nilsreiter** [comment]
Oh I overlooked that. Also wasn't aware of the entries in pom.

Should I also add the gmh tagger to the proprietary resources profile section in pom.xml?

**Comment by reckart** [comment]
Having the model in the proprietary resources profile is only required if we unit test for the model.

**Comment by reckart** [comment]
No, wrong ;) Actually it should be there in the dependency management section - yet.

**Comment by reckart** [comment]
Merged - thanks for the clean contribution!

**Pull request merged**
