### PR TITLE
Conll writers with coveredText parameter option 

### PR DESCRIPTION
**Pull request by Jibun**
Changes as we discussed in #1168

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@Jibun Jenkins reports checkstyle issues. If you build the code on you machine using Maven on the command line and/or install a Checkstyle plugin in your IDE you should be able to see them more easily. Or you can check the build log by clicking on the "details" next to Jenkins above and then click the "Console Output".

**Comment by Jibun** [comment]
@reckart I've fixed the Checkstyle errors

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@Jibun looks good :) Thanks! Before I merge the changes, it would be great if you could check out our contribution guidelines (https://dkpro.github.io/contributing/) and provide us with a CLA. 

Also, it would save me some time if you could re-write the commit comments in this PR to the following format:

```
#<ISSUE NUMBER> - <ISSUE TITLE>
<EMPTY LINE>
- <CHANGE 1>
- <CHANGE 2>
- <...>
```

Note that `#` normally introduces comments in git. You may have to reconfigure git before attempting an interactive rebase and switch it to another comment character: https://stackoverflow.com/questions/22936252/escape-comment-character-in-git-commit-message

**Comment by reckart** [comment]
Jenkins, can you test this please?

@Jibun branch looks of at from what I see here on GitHub.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
