### PR TITLE
Feature/1346 reader for annotated gigaword

### LINKED ISSUE #1346: Reader for Annotated Gigaword
Reader for Annotated Gigaword.

### PR DESCRIPTION
**Pull request by az79nefy**
Reader for Annotated Gigaword

* resolves #1346

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@az79nefy 

```
[WARNING] Unused declared dependencies found:
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.metadata-asl:jar:1.11.0-SNAPSHOT:compile
[WARNING]    eu.openminted.share.annotations:omtd-share-annotations-api:jar:3.0.2.7:compile
[WARNING]    org.apache.uima:uimafit-core:jar:2.4.0:compile
[WARNING]    commons-io:commons-io:jar:2.6:compile
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.io-asl:jar:1.11.0-SNAPSHOT:compile
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.parameter-asl:jar:1.11.0-SNAPSHOT:compile
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.testing-asl:jar:1.11.0-SNAPSHOT:test
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.resources-asl:jar:1.11.0-SNAPSHOT:compile
[WARNING]    junit:junit:jar:4.12:test
[WARNING]    org.apache.uima:uimaj-core:jar:2.10.3:compile
[WARNING]    de.tudarmstadt.ukp.dkpro.core:de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl:jar:1.11.0-SNAPSHOT:compile
```

Can we remove the dependency on guava?

**Comment by reckart** [comment]
A unit test would be nice as well :)

**Comment by az79nefy** [comment]
I am using guava for the AbstractIterator in `AnnotatedGigawordDocuments.java`, should I change that?

**Comment by reckart** [comment]
@az79nefy hm, I see what you use it for. Well, please add a unit test and fix the build - guava is a lower prio here atm.

**Comment by az79nefy** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@az79nefy there are many complaints from Checkstyle.

**Comment by az79nefy** [comment]
@reckart I have now used inception Checkstyle.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
@az79nefy Jenkins complains about missing license headers.

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
